# Generated by Django 3.2.9 on 2021-11-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='phone_number',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
