# Generated by Django 3.2.9 on 2021-11-07 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free_board', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='freepost',
        ),
    ]
